---
- name: Local Backup Playbook
  hosts: rtr1
  tasks:
    - name: Network Backup and Resource Manager
      ansible.builtin.include_role:
        name: network.backup.run
      vars:
        operation: backup
        data_store:
          local: "backups/2023-09-05/"
