---
- name: Remote Config Drift Detectiion Playbook
  hosts: network
  gather_facts: true
  tasks:
    - name: Network Backup and Resource Manager
      ansible.builtin.include_role:
        name: network.backup.run
      vars:
        operation: detect
        data_store:
          scm:
            origin:
              url: "https://github.com/rohitthakur2590/network_automation_backups"