---
- name: Remote Backup
  hosts: network
  tasks:
    - name: Network Backup and Resource Manager
      ansible.builtin.include_role:
        name: network.backup.run
      vars:
        operation: backup
        data_store:
          scm:
            origin:
              url: "https://github.com/rohitthakur2590/network_automation_backups"
              token: "{{ github_token }}"

