    # - name: Set Timestamp
    #   ansible.builtin.set_fact:
    #     time: "{{lookup('pipe','date \"+%Y-%m-%d\"')}}"
    #   run_once: true
              token: "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"




# TASK [network.backup.run : PRINT] ****************************************************************************************************************
# ok: [rtr1] => {
#     "msg": {
#         "backup_path": "backups/2023-09-05/rtr1.txt",
#         "changed": true,
#         "date": "2023-09-05",
#         "failed": false,
#         "time": "16:43:31"
#     }
# }
